import type { Config } from 'tailwindcss';

export default <Partial<Config>>{
    safelist: [
        '!rounded-button',
        'group-hover:scale-105',
        'bg-primary',
        'text-primary',
        'serif',
        'hover:underline',
        'rounded-button',
        'text-gray-900',
        'text-gray-500',
        'shadow-md',
        'h-64',
        'h-96',
        '!rounded-button',
        'group-hover:scale-105',
        'hover:bg-opacity-90',
        'rounded-lg',
        'shadow-md',
        'text-primary',
        'bg-primary',
        'bg-secondary',
        'bg-opacity-10',
        'bg-opacity-20',
        'text-gray-500',
        'text-gray-600',
        'text-gray-700',
        'text-gray-800',
        'text-gray-900',
        'text-white',
        'h-64',
        'h-80',
        'h-96',
        'w-full',
        'object-cover',
        'object-top',
        'transition',
        'duration-500',
        'font-medium',
        'font-semibold',
        'text-sm',
        'text-lg',
        'text-xl',
        'text-2xl',
        'text-3xl',
        'text-4xl',
        'text-5xl',
        'text-6xl',
        'text-center',
        'flex',
        'items-center',
        'justify-center',
        'gap-4',
        'gap-6',
        'gap-8',
        'px-6',
        'py-3',
        'py-20',
        'px-8',
        'container',
        'mx-auto',
    ],
    theme: {
        extend: {
            colors: {
                primary: '#d4b98c',
                secondary: '#f8f5f0',
            },
            borderRadius: {
                button: '8px',
            },
            fontFamily: {
                sans: ['Poppins', 'sans-serif'],
                serif: ['Playfair Display', 'serif'],
                fancy: ['Pacifico', 'cursive'],
            },
        },
    },
};
