on: [push]
jobs:
  Install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-base
          path: .
  Eslint:
    needs: Install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: code-base
      - name: Eslint
        run: npm run lint
  Typecheck:
    needs: Install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: code-base
      - name: Typecheck
        run: npm run typecheck

