on: [push]
jobs:
  Install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
  Eslint:
    needs: Install-dependencies
    runs-on: ubuntu-latest
    steps:
     - name: Eslint
       run: npm run lint
  Typecheck:
    needs: Install-dependencies
    runs-on: ubuntu-latest
    steps:
     - name: Typecheck
       run: npm run typecheck

